#!/bin/bash

if [ ! -f "$HOME/.ssh/id_rsa" ]; then
    ssh-keygen -t rsa -b 4096 -f $HOME/.ssh/id_rsa -N ""
fi

sudo apt update && install -y zsh tmux fzf ripgrep vim curl

mkdir -p $HOME/.antigen/
curl -L git.io/antigen > $HOME/.antigen/antigen.zsh

sudo chsh -s $(which zsh)
